apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grafana
  namespace: ${NAMESPACE}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grafana
  minReplicas: ${HPA_GRAF_MIN}
  maxReplicas: ${HPA_GRAF_MAX}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: ${HPA_GRAF_CPU}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: ${HPA_GRAF_MEM}
