# custom-values.yaml

# Namespace configuration
namespace:
  name: monitoring

# Site domain (used by Grafana Ingress)
site:
  domain: "monitor.k8s.didinmediagroup.com"

# Ingress class to use (examples: traefik or nginx)
ingress:
  className: "traefik"

# cert-manager configuration
certManager:
  # Use "letsencrypt-staging" for testing or "letsencrypt-prod" for production
  clusterIssuer: "letsencrypt-prod"
  # Email address used for Let's Encrypt registration and notifications
  email: "admin@didinmediagroup.com"

# Persistent storage configuration
storage:
  # Leave empty ("") to use the default StorageClass in your cluster
  className: ""
  prometheus:
    size: "20Gi"
  grafana:
    size: "5Gi"

# Grafana admin credentials (used to generate Kubernetes Secret)
grafana:
  adminUser: "admin"
  adminPassword: "password"
