apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: ${NAMESPACE}
spec:
  secretName: grafana-tls
  issuerRef:
    name: ${CLUSTER_ISSUER}
    kind: ClusterIssuer
  commonName: ${DOMAIN}
  dnsNames:
    - ${DOMAIN}
